/*-----------------------------------------------------------------------------

  fontgen.c

  Build-time tool. Renders the signage / HUD fonts to 1-bpp glyph bitmaps and
  writes font_data.c, so the game itself needs neither FreeType, fontconfig, nor
  the .ttf files at run time -- the glyphs are compiled straight in.

  It reproduces EXACTLY the baking that Render.cpp's RenderLoadFonts() used to do
  at startup (same FONT_SIZE, same >127 threshold, same bottom-up row flip, same
  glBitmap metrics), so the on-screen result is unchanged.

  Compiled as C++ purely so it can include Texture.h for the FONT_SIZE formula.
  Build & run:  make regen-fonts   (needs freetype2 + the fonts/ TTFs)

-----------------------------------------------------------------------------*/

#include <ft2build.h>
#include FT_FREETYPE_H
#include <cstdio>
#include <cstdlib>

#include "Texture.h"   // LOGO_PIXELS -> FONT_SIZE

// Must match Render.cpp's FONT_SIZE define exactly.
#define FONT_SIZE   (LOGO_PIXELS - LOGO_PIXELS / 8)
#define FIRST_CHAR  32
#define LAST_CHAR   126
#define NGLYPH      (LAST_CHAR - FIRST_CHAR + 1)

// Must match the fonts[] table in Render.cpp (same order -> same font index).
static const char* fonts[] = {
  "fonts/Anton-Regular.ttf",
  "fonts/ArchivoBlack-Regular.ttf",
  "fonts/BebasNeue-Regular.ttf",
  "fonts/RussoOne-Regular.ttf",
  "fonts/Rajdhani-Bold.ttf",
  "fonts/SairaCondensed-Bold.ttf",
  "fonts/Audiowide-Regular.ttf",
};
static const int NFONT = sizeof (fonts) / sizeof (fonts[0]);

int main (void)
{
  FT_Library lib;
  if (FT_Init_FreeType (&lib)) { fprintf (stderr, "FT_Init_FreeType failed\n"); return 1; }

  FILE* out = fopen ("font_data.c", "w");
  if (!out) { fprintf (stderr, "cannot open font_data.c for writing\n"); return 1; }

  fprintf (out,
    "/* GENERATED by fontgen.c -- DO NOT EDIT.\n"
    "   %d fonts x %d glyphs (ASCII %d..%d) baked at FONT_SIZE=%d.\n"
    "   Regenerate with: make regen-fonts */\n"
    "#include \"font_data.h\"\n\n",
    NFONT, NGLYPH, FIRST_CHAR, LAST_CHAR, FONT_SIZE);

  for (int f = 0; f < NFONT; f++) {
    FT_Face face;
    if (FT_New_Face (lib, fonts[f], 0, &face)) {
      fprintf (stderr, "cannot open font %s\n", fonts[f]);
      return 1;
    }
    FT_Set_Char_Size (face, FONT_SIZE * 64, 0, 72, 72);

    // --- glyph bitmap byte arrays ---
    for (int c = FIRST_CHAR; c <= LAST_CHAR; c++) {
      FT_Load_Char (face, c, FT_LOAD_RENDER);
      FT_Glyph_Metrics& m  = face->glyph->metrics;
      FT_Bitmap&        bm = face->glyph->bitmap;
      int w = m.width  >> 6;
      int h = m.height >> 6;
      int stride = (w + 7) / 8;
      int n = h * stride;
      if (n <= 0)
        continue;
      unsigned char* bits = (unsigned char*)calloc (n, 1);
      for (int y = 0; y < h; y++) {
        int yOff = (h - y - 1) * stride;       // freetype/gl opposite row order
        for (int x = 0; x < w; x++)
          if (bm.buffer[y * bm.width + x] > 127)
            bits[yOff + (x / 8)] |= (1 << (7 - (x % 8)));
      }
      fprintf (out, "static const unsigned char g%d_%d[%d]={", f, c, n);
      for (int b = 0; b < n; b++)
        fprintf (out, "%s%u", b ? "," : "", (unsigned)bits[b]);
      fprintf (out, "};\n");
      free (bits);
    }

    // --- per-font glyph table ---
    fprintf (out, "static const Glyph f%d[%d]={\n", f, NGLYPH);
    for (int c = FIRST_CHAR; c <= LAST_CHAR; c++) {
      FT_Load_Char (face, c, FT_LOAD_RENDER);
      FT_Glyph_Metrics& m  = face->glyph->metrics;
      FT_Vector&        ad = face->glyph->advance;
      int    w = m.width  >> 6;
      int    h = m.height >> 6;
      int    n = h * ((w + 7) / 8);
      double xorig = -(m.horiBearingX / 64.0);
      double yorig = (m.height - m.horiBearingY) / 64.0;
      double xmove = ad.x / 64.0;
      double ymove = ad.y / 64.0;
      if (n > 0)
        fprintf (out, "  {%d,%d,%.9g,%.9g,%.9g,%.9g,g%d_%d},\n",
                 w, h, xorig, yorig, xmove, ymove, f, c);
      else
        fprintf (out, "  {%d,%d,%.9g,%.9g,%.9g,%.9g,0},\n",
                 w, h, xorig, yorig, xmove, ymove);
    }
    fprintf (out, "};\n\n");
    FT_Done_Face (face);
  }

  fprintf (out, "const Glyph* const font_glyphs[]={");
  for (int f = 0; f < NFONT; f++)
    fprintf (out, "%sf%d", f ? "," : "", f);
  fprintf (out, "};\n");
  fprintf (out, "const int font_count=%d;\n", NFONT);
  fprintf (out, "const int font_first_char=%d;\n", FIRST_CHAR);
  fprintf (out, "const int font_glyph_count=%d;\n", NGLYPH);

  fclose (out);
  FT_Done_FreeType (lib);
  fprintf (stderr, "fontgen: wrote font_data.c (%d fonts x %d glyphs, FONT_SIZE=%d)\n",
           NFONT, NGLYPH, FONT_SIZE);
  return 0;
}
